from langchain_core.messages import AIMessage
from .state import State
import json
from langchain_core.output_parsers import StrOutputParser
from langchain_core.messages import AIMessage


def makeGenPlot(llm):
    def genPlot(state: State):
        """
        Generates a Plotly JSON visualization by prompting the LLM directly.
        This is more efficient than generating and executing Python code.
        """
        prompt = f"""
You are an expert in data visualization. Your task is to generate a Plotly JSON chart object based on the user's query and the provided data.

**User's Question:**
{state["question"]}

**Analysis Summary:**
{state["answer"]}

**Data:**
```
{state["result"]}
```

**Instructions:**
1. Analyze the user's question, the summary, and the data.
2. Generate a complete and valid Plotly JSON object for a chart that best visualizes the information.
3. **IMPORTANT**: Your output must be ONLY the Plotly JSON object. Do not include any explanations, comments, or markdown formatting like ```json ... ```.

**Example of expected JSON output:**
{{
  "data": [
    {{
      "type": "bar",
      "x": ["Category A", "Category B", "Category C"],
      "y": [10, 20, 15]
    }}
  ],
  "layout": {{
    "title": "Bar Chart Title From Question"
  }}
}}

Now, generate the Plotly JSON based on the user's question and the provided data.
"""

        chain = llm | StrOutputParser()
        plotly_json_str = chain.invoke(prompt)

        # Clean up the response to ensure it's just JSON
        if plotly_json_str.strip().startswith("```json"):
            plotly_json_str = plotly_json_str.strip()[8:-3].strip()
        elif plotly_json_str.strip().startswith("```"):
            plotly_json_str = plotly_json_str.strip()[3:-3].strip()

        try:
            # Validate that the output is valid JSON
            json.loads(plotly_json_str)
            return {"plotly_plot": plotly_json_str, "chat_history": [AIMessage(content="Generated a plot.")]}
        except json.JSONDecodeError as e:
            print(f"Error in genPlot: Invalid JSON generated by LLM. Error: {e}")
            print(f"Generated string was:\n{plotly_json_str}")
            return {"plotly_plot": "{}", "chat_history": [AIMessage(content="Failed to generate a plot due to a data formatting error.")]}
        except Exception as e:
            print(f"An unexpected error occurred in genPlot: {e}")
            return {"plotly_plot": "{}", "chat_history": [AIMessage(content="Failed to generate a plot due to an unexpected error.")]}

    return genPlot


